<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
    	
        <ul>
    	
    	<?php foreach ($productList as $product):?>
    		<li>
    			<article>
    				
    				<h3><?= $product["name"]?></h3>
    				<p> <?= $product["description"]?></p>
    				<p><?=Tools::getPrettyPrice($product['priceHT'])?></p>
    				<img src="<?= $wwwUrl ?>/images/meals/<?= $product['photo'] ?>">
    			
    			</article>
    		</li>
    	<?php endforeach ?>
    	</ul>
      

     </tbody>
</table>


