<h3>Récapitulatif de la commande</h3>

<table>
<?php foreach ($productList as $product ):?>


	<tr>
		<td><?= $product['quantity']?></td>
		
		<td><?= $product['name']?></td>
		
		<td><?= Tools::getPrettyPrice(Tools::getPriceTTC($product['priceHT']))?></td>
		
		<td><?= Tools::getPrettyPrice(Tools::getPriceTTC($product['priceHT']*$product['quantity']))?></td>	
		
		<td>
			<button class="button-delete" type="button" data-id ="<? $product['id']?>">Supprimer>

			</button>
		</td>
	

	</tr>

<?php endforeach ?>

</table>
