
<h2>Passer une Commande</h2>

<div class="add">
    <label>
        Produits

        <select>
            <?php foreach ($productList as $product):?>
                
                <option value="<?=$product['id'] ?>"><?=$product["name"]?></option>
            
            <?php endforeach ?>
        </select>
    </label>
    
    <div class ="product-info"></div>
    
    <div class="quantity">
        <label>Quantité<input type="number" name="quantity"></label>
        <button type="button" class="btn-add">Ajouter</button>
    </div>



     <div class="box-cart"></div>

     <form action="<?= $requestUrl ?>/" method="post">
        <button class="button-valid" type="submit" >Valider la commande</button>
    </form>

</div>

<script src="<?= $wwwUrl ?>/js/order.js"></script>

