<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<title>Jeu arena</title>
	<link rel="stylesheet" type="text/css" href="../arena.css">
</head>
<body>
<header>
	<ul>
		<li> <a href="http://localhost/Developpement/jeu_arena/public/index.phtml">Accueil</a></li>
		<li> <a href="http://localhost/Developpement/jeu_arena/services/service.php">Créer un personnage</a></li>
		<li> <a href="http://localhost/Developpement/jeu_arena/public/listpers.phtml">Liste des personnages</a></li>
		<li> <a href="">L'arène</a></li>
	</ul>
</header>
<main>
	<form method="post" action="addero.php"></form>
	<input type="text" name="nom" placeholder=" nom">
	<input type="text" name="ph" placeholder=" point de vie">
	<input type="text" name="armor" placeholder="armure ">
	<input type="text" name="weapon" placeholder="arme ">
	<input type="text" name="avatar" placeholder="avatar">
	<button>Sauver</button>
</main>

</body>
</html>